### PR TITLE
0.2.0 - resource wrappers for workflow clients.

### PR DESCRIPTION
**Pull request by byubean**
See `test_manager.py` for an example of the client behavior this PR enables. 

Rather than have clients interact with the verbose, easy-to-botch signature of `record_external_event` or `send_event`, these wrappers give the client what looks like a regular resource (e.g. a `queue` or an `event`). Less to mess up. Cleaner-looking code.

### CODE REVIEW

**Comment by ABCambridge** [comment]
@byubean I tried removing that sleep statement and that test started failing, so I removed your comment since it looks like sleep needs to stay.

**Review by ABCambridge — APPROVED** [review]
Looks good

**Comment by kjstanding** [comment]
In regards to that sleep statement in `test_get_queue`, I see how stream_resources could eliminate the need for it. This is a nice wrapper that makes interacting with resources a lot simpler. I think going over the changes in manager.py and specifically what the wrapper functions are doing would be nice. Maybe spend like 5 minutes during our weekly meeting

**Review by kjstanding — APPROVED** [review]
Looks good

**Comment by kjstanding** [comment]
After looking at potentially cleaning up the tests for this change utilizing `stream_resources` I realized that we might have more work to do with `stream_resources` and being able to use it through a workflow manager context. Maybe we ought to close this PR and create new issues for 1. integrating `stream_resources` into manager and 2. cleaning up tests with `stream_resources`

**Pull request merged**
